<a href="https://colab.research.google.com/github/printsanya/NLP-PROJECTS/blob/main/fake_news_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df=pd.read_csv('/content/WELFake_Dataset.csv')

In [5]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [18]:
df=df.dropna()

In [19]:
x=df.drop('label',axis=1)

In [20]:
y=df['label']

In [21]:
import tensorflow as tf

In [22]:
tf.__version__


'2.18.0'

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [24]:
voc_size=5000
message=x.copy()
message.reset_index(inplace=True)

In [25]:
import nltk
import re
from nltk.corpus import stopwords

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [27]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
66537
66538
66539
66540
66541
66542
66543
66544
66545
66546
66547
66548
66549
66550
66551
66552
66553
66554
66555
66556
66557
66558
66559
66560
66561
66562
66563
66564
66565
66566
66567
66568
66569
66570
66571
66572
66573
66574
66575
66576
66577
66578
66579
66580
66581
66582
66583
66584
66585
66586
66587
66588
66589
66590
66591
66592
66593
66594
66595
66596
66597
66598
66599
66600
66601
66602
66603
66604
66605
66606
66607
66608
66609
66610
66611
66612
66613
66614
66615
66616
66617
66618
66619
66620
66621
66622
66623
66624
66625
66626
66627
66628
66629
66630
66631
66632
66633
66634
66635
66636
66637
66638
66639
66640
66641
66642
66643
66644
66645
66646
66647
66648
66649
66650
66651
66652
66653
66654
66655
66656
66657
66658
66659
66660
66661
66662
66663
66664
66665
66666
66667
66668
66669
66670
66671
66672
66673
66674
66675
66676
66677
66678
66679
66680
66681
66682
66683
66684
66685
66686
66687
66688
66689
66690
66691
66692
66693
66694
6

In [30]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[137, 920, 1400, 1288, 248, 4053, 3057, 331, 1328, 428, 1299, 3255],
 [4876,
  368,
  1372,
  4592,
  151,
  2195,
  4770,
  677,
  4900,
  2676,
  3969,
  1923,
  3603,
  3255],
 [3323, 3836, 2302, 246, 4008, 1891, 4, 3642, 2986, 338, 1063, 4677],
 [178, 2922, 1334, 341, 2852, 3643, 694, 4157, 4640, 4479, 1294],
 [3764, 4, 3327, 918, 1831, 2827, 2226, 3893, 3327],
 [8, 544, 689, 14, 3934, 3163, 1122, 2042, 1217, 2437, 1425],
 [3708, 4509, 457, 2040, 2922, 3574, 1891, 4420, 3734, 3255],
 [4075,
  960,
  4093,
  4635,
  4010,
  547,
  1958,
  4433,
  2520,
  4075,
  4251,
  3811,
  1383,
  3477,
  3255],
 [1643, 1976, 4981, 4852, 3908, 3240, 816, 1976],
 [1146, 4162, 4392, 717, 4080, 4806, 1230, 959],
 [815, 3395, 3555, 92, 860, 2026, 2448, 3618, 2448, 157],
 [169, 1091, 2040, 609, 1693, 70, 1501, 3103, 2394],
 [4397, 3830, 3957, 1091, 3351, 2181, 879, 4821, 1519, 776, 2184],
 [1909, 4042, 990, 2597, 962, 243, 3829, 2358, 1112, 1411],
 [909, 4310, 3120, 882, 1054, 3708, 3989],
 [2865, 

In [31]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  428 1299 3255]
 [   0    0    0 ... 1923 3603 3255]
 [   0    0    0 ...  338 1063 4677]
 ...
 [   0    0    0 ...  848 3753 3872]
 [   0    0    0 ... 2499 2746  596]
 [   0    0    0 ... 4510 4821  648]]


In [32]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [36]:

len(embedded_docs)

71537

In [38]:
y.shape

(71537,)

In [34]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [35]:
X_final.shape,y_final.shape

((71537, 20), (71537,))

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 32s 39ms/step - accuracy: 0.8065 - loss: 0.3978 - val_accuracy: 0.8956 - val_loss: 0.2476
Epoch 2/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 41s 39ms/step - accuracy: 0.9110 - loss: 0.2154 - val_accuracy: 0.8973 - val_loss: 0.2456
Epoch 3/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 48s 48ms/step - accuracy: 0.9292 - loss: 0.1777 - val_accuracy: 0.8977 - val_loss: 0.2469
Epoch 4/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 39s 46ms/step - accuracy: 0.9407 - loss: 0.1507 - val_accuracy: 0.8949 - val_loss: 0.2702
Epoch 5/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 37s 40ms/step - accuracy: 0.9482 - loss: 0.1349 - val_accuracy: 0.8937 - val_loss: 0.2907
Epoch 6/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 29s 39ms/step - accuracy: 0.9566 - loss: 0.1144 - val_accuracy: 0.8892 - val_loss: 0.3151
Epoch 7/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 29s 38ms/step - accuracy: 0.9640 - loss: 0.0967 - val_accuracy: 0.8914 - val_loss: 0.3491
Epoch 8/10


In [42]:
# from tensorflow.keras.layers import Dropout
# ## Creating model
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(Dropout(0.3))
# model.add(LSTM(100))
# model.add(Dropout(0.3))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [54]:
y_pred=model.predict(X_test)

738/738 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step


In [55]:
from sklearn.metrics import confusion_matrix
y_pred_binary = np.where(y_pred > 0.5, 1, 0)
confusion_matrix(y_test,y_pred_binary)

array([[4374, 7319],
       [4533, 7382]])

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_binary)

0.4979667909183328